#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

suppy-config-post-extract() {
  declare APP="$1" TMPDIR="$2"

  dokku_col_log_info1_quiet "Checking for config supplied in repo"

  if [[ -d "$TMPDIR/.dokku" ]] && [[ "$(ls -A "$TMPDIR/.dokku")" ]]; then
    output=$(cp -r "$TMPDIR/.dokku/." "$DOKKU_ROOT/$APP")
    dokku_log_verbose_quiet "$output"

    if [[ "$(ls -A "$TMPDIR/.dokku/crontab")" ]]; then
        output=$(sudo cp -r "$TMPDIR/.dokku/crontab" "/etc/cron.d/$APP")
        dokku_log_verbose_quiet "$output"
        sudo service cron restart
    fi
  fi
}

suppy-config-post-extract "$@"
