#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

copy_config() {
  local APP="$1"
  local TMPDIR="$2"
  trap 'rm -rf "$TMP_WORK_DIR" > /dev/null' RETURN

  dokku_col_log_info1_quiet "Checking for config supplied in repo"

  if [[ -d "$TMPDIR/.dokku" ]] && [[ "$(ls -A "$TMPDIR/.dokku")" ]]; then
    output=$(cp -r "$TMPDIR/.dokku/." "$DOKKU_ROOT/$APP")
    dokku_log_verbose_quiet "$output"
  fi
}
copy_config "$1" "$2"
