#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

APP="$1"
TMPDIR=$(mktemp -d)

echo -n "-----> Checking for config supplied in repo ... "

cd "$TMPDIR" && git clone "$DOKKU_ROOT"/"$APP" repo > /dev/null 2>&1

if [ -e repo/.dokku/* ] ; then
	echo -n "found, importing: "
	for file in repo/.dokku/* ; do
		echo -n $(basename "$file")
		cp "$file" "$DOKKU_ROOT"/"$APP"/
	done
	echo " OK."
else
	echo "no config supplied."
fi
trap "rm -rf '$TMPDIR'" SIGHUP SIGINT SIGTERM