#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

destroy_temp_dir() {
  local APP="$1"
  local TMPDIR
  TMPDIR=$(mktemp -d)
  trap 'rm -rf "$TMP_WORK_DIR" > /dev/null' RETURN

  dokku_col_log_info1_quiet "Checking for config supplied in repo"

  cd "$TMPDIR" && git clone -q "$DOKKU_ROOT/$APP" repo > /dev/null 2>&1

  if [[ -d "$TMPDIR/repo/.dokku" ]] && [[ "$(ls -A "$TMPDIR/repo/.dokku")" ]]; then
    output=$(cp -r "$TMPDIR/repo/.dokku/." "$DOKKU_ROOT/$APP")
    dokku_log_verbose_quiet "$output"
  fi
}

destroy_temp_dir "$1"
